#!/usr/bin/ruby

#include the tuple class
load 'tuple.rb'
require 'date'

#a hash that maps a file to tuple that store a commit's information
$map = Hash.new
#the longest word in maps
$longest = 0

def traverse(start)
  Dir.foreach(start) do |x|
    path = File.join(start, x)

    if(x == '.' || x == '..')
      next
    elsif File.file?(path) 
      if File.readable?(x)
  	$longest = $longest < x.length ? x.length : $longest
        parse(x)
      end
    else
      traverse(path)
    end
  end
end

def parse(file)
  commit = `git log #{file}`
  lines = commit.split("\n")
  info = Tuple.new
  
  lines.each do |w|
    first = w.split.first
    words = w.split.drop(1)
    
    if !words.last.nil? && (words.last.include? "<") 
      words = words.take(words.length - 1)
    end
    next_value = words.join(' ') 

    if first.eql? "commit"
      info.changeCommit(next_value[0..5])
    elsif first.eql? 'Author:'
      info.changeAuthor(next_value)
    elsif first.eql? 'Date:'
      #when there is a time value, push the tuple to the array of commits
      #and make info a new tuple
      info.changeDate(DateTime.parse(next_value))
    end
  end
  
  $map.store(file, info)
end

#print hash
def print_hash
  $map.each do |key, value|
    if(!(key.nil? || value.nil?))
      puts "#{value.getDate} [#{value.getCommit}]: #{key}" +
            " " * ($longest - key.length + 1) +
            "(#{value.getAuthor})"
    end
  end
end

if(ARGV.length > 1)
  puts "There can only be one directory"
  exit 1
else
  target_path = Dir.pwd
  if !ARGV.empty?
    target_path = target_path + "/" + ARGV[0]
  end

  puts target_path
  traverse(target_path)
  
  print_hash
end
